<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.crawl.escargot_factory' shared service.

include_once \dirname(__DIR__, 4).'\\vendor\\contao\\core-bundle\\src\\Crawl\\Escargot\\Factory.php';
include_once \dirname(__DIR__, 4).'\\vendor\\terminal42\\escargot\\src\\Subscriber\\SubscriberInterface.php';
include_once \dirname(__DIR__, 4).'\\vendor\\contao\\core-bundle\\src\\Crawl\\Escargot\\Subscriber\\EscargotSubscriberInterface.php';
include_once \dirname(__DIR__, 4).'\\vendor\\terminal42\\escargot\\src\\EscargotAwareInterface.php';
include_once \dirname(__DIR__, 4).'\\vendor\\terminal42\\escargot\\src\\Subscriber\\ExceptionSubscriberInterface.php';
include_once \dirname(__DIR__, 4).'\\vendor\\psr\\log\\Psr\\Log\\LoggerAwareInterface.php';
include_once \dirname(__DIR__, 4).'\\vendor\\terminal42\\escargot\\src\\EscargotAwareTrait.php';
include_once \dirname(__DIR__, 4).'\\vendor\\psr\\log\\Psr\\Log\\LoggerAwareTrait.php';
include_once \dirname(__DIR__, 4).'\\vendor\\terminal42\\escargot\\src\\SubscriberLoggerTrait.php';
include_once \dirname(__DIR__, 4).'\\vendor\\contao\\core-bundle\\src\\Crawl\\Escargot\\Subscriber\\BrokenLinkCheckerSubscriber.php';
include_once \dirname(__DIR__, 4).'\\vendor\\contao\\core-bundle\\src\\Crawl\\Escargot\\Subscriber\\SearchIndexSubscriber.php';

$this->services['contao.crawl.escargot_factory'] = $instance = new \Contao\CoreBundle\Crawl\Escargot\Factory(($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()), ($this->services['contao.framework'] ?? $this->getContao_FrameworkService()), [], []);

$a = ($this->services['translator'] ?? $this->getTranslatorService());

$b = new \Contao\CoreBundle\Crawl\Escargot\Subscriber\BrokenLinkCheckerSubscriber($a);

$c = ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService());

$b->setLogger($c);
$d = new \Contao\CoreBundle\Crawl\Escargot\Subscriber\SearchIndexSubscriber(($this->services['contao.search.indexer'] ?? $this->load('getContao_Search_IndexerService.php')), $a);
$d->setLogger($c);

$instance->addSubscriber($b);
$instance->addSubscriber($d);

return $instance;
