<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.command.debug-plugins' shared service.

include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\console\\Command\\Command.php';
include_once \dirname(__DIR__, 4).'\\vendor\\contao\\manager-bundle\\src\\Command\\DebugPluginsCommand.php';

$this->privates['contao.command.debug-plugins'] = $instance = new \Contao\ManagerBundle\Command\DebugPluginsCommand(($this->services['kernel'] ?? $this->get('kernel', 1)));

$instance->setName('debug:plugins');

return $instance;
