<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.security.authentication_listener.contao_frontend' shared service.

include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\security-http\\Firewall\\AbstractListener.php';
include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\security-http\\Firewall\\ListenerInterface.php';
include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\security-http\\Firewall\\LegacyListenerTrait.php';
include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\security-http\\Firewall\\AbstractAuthenticationListener.php';
include_once \dirname(__DIR__, 4).'\\vendor\\contao\\core-bundle\\src\\Security\\Authentication\\ContaoLoginAuthenticationListener.php';
include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\security-http\\Session\\SessionAuthenticationStrategyInterface.php';
include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\security-http\\Session\\SessionAuthenticationStrategy.php';
include_once \dirname(__DIR__, 4).'\\vendor\\scheb\\two-factor-bundle\\Security\\Authentication\\Token\\TwoFactorTokenFactoryInterface.php';
include_once \dirname(__DIR__, 4).'\\vendor\\scheb\\two-factor-bundle\\Security\\Authentication\\Token\\TwoFactorTokenFactory.php';

$this->privates['contao.security.authentication_listener.contao_frontend'] = $instance = new \Contao\CoreBundle\Security\Authentication\ContaoLoginAuthenticationListener(($this->services['security.token_storage'] ?? $this->getSecurity_TokenStorageService()), ($this->privates['security.authentication.manager'] ?? $this->getSecurity_Authentication_ManagerService()), ($this->privates['security.authentication.session_strategy'] ?? ($this->privates['security.authentication.session_strategy'] = new \Symfony\Component\Security\Http\Session\SessionAuthenticationStrategy('migrate'))), ($this->privates['security.http_utils'] ?? $this->load('getSecurity_HttpUtilsService.php')), 'contao_frontend', ($this->privates['contao.security.authentication_success_handler'] ?? $this->load('getContao_Security_AuthenticationSuccessHandlerService.php')), ($this->privates['contao.security.authentication_failure_handler'] ?? $this->load('getContao_Security_AuthenticationFailureHandlerService.php')), ['require_previous_session' => false], ($this->privates['scheb_two_factor.default_token_factory'] ?? ($this->privates['scheb_two_factor.default_token_factory'] = new \Scheb\TwoFactorBundle\Security\Authentication\Token\TwoFactorTokenFactory())), ($this->privates['monolog.logger.security'] ?? $this->load('getMonolog_Logger_SecurityService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));

$instance->setRememberMeServices(($this->privates['security.authentication.rememberme.services.simplehash.contao_frontend.two_factor_decorator'] ?? $this->load('getSecurity_Authentication_Rememberme_Services_Simplehash_ContaoFrontend_TwoFactorDecoratorService.php')));

return $instance;
