<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.Contao\CoreBundle\Command\MigrateCommand' shared service.

include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\console\\Command\\Command.php';
include_once \dirname(__DIR__, 4).'\\vendor\\contao\\core-bundle\\src\\Command\\MigrateCommand.php';

return $this->services['console.command.public_alias.Contao\\CoreBundle\\Command\\MigrateCommand'] = new \Contao\CoreBundle\Command\MigrateCommand(($this->privates['Contao\\CoreBundle\\Migration\\MigrationCollection'] ?? $this->load('getMigrationCollectionService.php')), ($this->services['contao.resource_locator'] ?? $this->load('getContao_ResourceLocatorService.php')), \dirname(__DIR__, 4), ($this->services['contao.framework'] ?? $this->getContao_FrameworkService()), ($this->services['contao.installer'] ?? $this->load('getContao_InstallerService.php')));
