<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0xTvtZl\appContao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0xTvtZl/appContao_ManagerBundle_HttpKernel_ContaoKernelProdContainer.php') {
    touch(__DIR__.'/Container0xTvtZl.legacy');

    return;
}

if (!\class_exists(appContao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, false)) {
    \class_alias(\Container0xTvtZl\appContao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, appContao_ManagerBundle_HttpKernel_ContaoKernelProdContainer::class, false);
}

return new \Container0xTvtZl\appContao_ManagerBundle_HttpKernel_ContaoKernelProdContainer([
    'container.build_hash' => '0xTvtZl',
    'container.build_id' => '23ed24c5',
    'container.build_time' => 1591281663,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0xTvtZl');
