<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.listener.pretty_error_screens' shared service.

include_once \dirname(__DIR__, 4).'\\vendor\\contao\\core-bundle\\src\\EventListener\\PrettyErrorScreenListener.php';

return $this->privates['contao.listener.pretty_error_screens'] = new \Contao\CoreBundle\EventListener\PrettyErrorScreenListener(true, ($this->services['twig'] ?? $this->getTwigService()), ($this->services['contao.framework'] ?? $this->getContao_FrameworkService()), ($this->services['security.helper'] ?? $this->getSecurity_HelperService()));
