<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.listener.search_index' shared service.

include_once \dirname(__DIR__, 4).'\\vendor\\contao\\core-bundle\\src\\EventListener\\SearchIndexListener.php';

return $this->privates['contao.listener.search_index'] = new \Contao\CoreBundle\EventListener\SearchIndexListener(($this->services['contao.search.indexer'] ?? $this->load('getContao_Search_IndexerService.php')), '/_fragment', 3);
