<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Contao\CoreBundle\Controller\InsertTagsController' shared service.

include_once \dirname(__DIR__, 4).'\\vendor\\contao\\core-bundle\\src\\Controller\\InsertTagsController.php';

return $this->services['Contao\\CoreBundle\\Controller\\InsertTagsController'] = new \Contao\CoreBundle\Controller\InsertTagsController(($this->services['contao.framework'] ?? $this->getContao_FrameworkService()));
