<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ozikhm4' shared service.

return $this->privates['.service_locator.ozikhm4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'Contao\\CoreBundle\\Controller\\FrontendController::cronAction' => ['privates', '.service_locator.mt6FK0z', 'get_ServiceLocator_Mt6FK0zService.php', true],
    'Contao\\CoreBundle\\Controller\\FrontendModule\\TwoFactorController::__invoke' => ['privates', '.service_locator.3G5BiB9', 'get_ServiceLocator_3G5BiB9Service.php', true],
    'Contao\\CoreBundle\\Controller\\FrontendController:cronAction' => ['privates', '.service_locator.mt6FK0z', 'get_ServiceLocator_Mt6FK0zService.php', true],
    'Contao\\CoreBundle\\Controller\\FrontendModule\\TwoFactorController:__invoke' => ['privates', '.service_locator.3G5BiB9', 'get_ServiceLocator_3G5BiB9Service.php', true],
    'Contao\\CoreBundle\\Controller\\FrontendModule\\TwoFactorController' => ['privates', '.service_locator.3G5BiB9', 'get_ServiceLocator_3G5BiB9Service.php', true],
], [
    'Contao\\CoreBundle\\Controller\\FrontendController::cronAction' => '?',
    'Contao\\CoreBundle\\Controller\\FrontendModule\\TwoFactorController::__invoke' => '?',
    'Contao\\CoreBundle\\Controller\\FrontendController:cronAction' => '?',
    'Contao\\CoreBundle\\Controller\\FrontendModule\\TwoFactorController:__invoke' => '?',
    'Contao\\CoreBundle\\Controller\\FrontendModule\\TwoFactorController' => '?',
]);
