<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Contao\CoreBundle\Security\TwoFactor\BackupCodeManager' shared service.

include_once \dirname(__DIR__, 4).'\\vendor\\scheb\\two-factor-bundle\\Security\\TwoFactor\\Backup\\BackupCodeManagerInterface.php';
include_once \dirname(__DIR__, 4).'\\vendor\\contao\\core-bundle\\src\\Security\\TwoFactor\\BackupCodeManager.php';

return $this->services['Contao\\CoreBundle\\Security\\TwoFactor\\BackupCodeManager'] = new \Contao\CoreBundle\Security\TwoFactor\BackupCodeManager();
