<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.security.authentication_provider.contao_frontend.two_factor_decorator' shared service.

include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\security-core\\Authentication\\Provider\\AuthenticationProviderInterface.php';
include_once \dirname(__DIR__, 4).'\\vendor\\scheb\\two-factor-bundle\\Security\\Authentication\\Provider\\AuthenticationProviderDecorator.php';
include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\security-core\\Authentication\\Provider\\UserAuthenticationProvider.php';
include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\security-core\\Authentication\\Provider\\DaoAuthenticationProvider.php';
include_once \dirname(__DIR__, 4).'\\vendor\\contao\\core-bundle\\src\\Security\\Authentication\\Provider\\AuthenticationProvider.php';
include_once \dirname(__DIR__, 4).'\\vendor\\scheb\\two-factor-bundle\\Security\\Authentication\\Provider\\TwoFactorAuthenticationProvider.php';
include_once \dirname(__DIR__, 4).'\\vendor\\scheb\\two-factor-bundle\\Security\\TwoFactor\\Backup\\BackupCodeManagerInterface.php';
include_once \dirname(__DIR__, 4).'\\vendor\\contao\\core-bundle\\src\\Security\\TwoFactor\\BackupCodeManager.php';
include_once \dirname(__DIR__, 4).'\\vendor\\scheb\\two-factor-bundle\\Security\\TwoFactor\\AuthenticationContextFactoryInterface.php';
include_once \dirname(__DIR__, 4).'\\vendor\\scheb\\two-factor-bundle\\Security\\TwoFactor\\AuthenticationContextFactory.php';

$a = ($this->privates['scheb_two_factor.authenticated_token_handler'] ?? $this->load('getSchebTwoFactor_AuthenticatedTokenHandlerService.php'));
$b = ($this->privates['scheb_two_factor.authentication_context_factory'] ?? ($this->privates['scheb_two_factor.authentication_context_factory'] = new \Scheb\TwoFactorBundle\Security\TwoFactor\AuthenticationContextFactory('Scheb\\TwoFactorBundle\\Security\\TwoFactor\\AuthenticationContext')));
$c = ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()));

return $this->privates['contao.security.authentication_provider.contao_frontend.two_factor_decorator'] = new \Scheb\TwoFactorBundle\Security\Authentication\Provider\AuthenticationProviderDecorator(new \Contao\CoreBundle\Security\Authentication\Provider\AuthenticationProvider(($this->privates['contao.security.frontend_user_provider'] ?? $this->load('getContao_Security_FrontendUserProviderService.php')), ($this->privates['contao.security.user_checker'] ?? $this->load('getContao_Security_UserCheckerService.php')), 'contao_frontend', ($this->services['security.encoder_factory'] ?? $this->load('getSecurity_EncoderFactoryService.php')), ($this->services['contao.framework'] ?? $this->getContao_FrameworkService()), new \Scheb\TwoFactorBundle\Security\Authentication\Provider\TwoFactorAuthenticationProvider('contao_frontend', [], ($this->privates['scheb_two_factor.provider_registry'] ?? $this->getSchebTwoFactor_ProviderRegistryService()), ($this->services['Contao\\CoreBundle\\Security\\TwoFactor\\BackupCodeManager'] ?? ($this->services['Contao\\CoreBundle\\Security\\TwoFactor\\BackupCodeManager'] = new \Contao\CoreBundle\Security\TwoFactor\BackupCodeManager())), ($this->privates['scheb_two_factor.provider_preparation_recorder'] ?? $this->getSchebTwoFactor_ProviderPreparationRecorderService())), $a, $b, $c, ($this->services['contao.security.two_factor.trusted_device_manager'] ?? $this->load('getContao_Security_TwoFactor_TrustedDeviceManagerService.php'))), $a, $b, ($this->services['security.firewall.map'] ?? $this->getSecurity_Firewall_MapService()), $c);
