<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.image.deferred_image_storage' shared service.

include_once \dirname(__DIR__, 4).'\\vendor\\contao\\image\\src\\DeferredImageStorageInterface.php';
include_once \dirname(__DIR__, 4).'\\vendor\\contao\\image\\src\\DeferredImageStorageFilesystem.php';

return $this->privates['contao.image.deferred_image_storage'] = new \Contao\Image\DeferredImageStorageFilesystem((\dirname(__DIR__, 4).'/assets/images'), ($this->services['filesystem'] ?? ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem())));
