<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.search.indexer' shared service.

include_once \dirname(__DIR__, 4).'\\vendor\\contao\\core-bundle\\src\\Search\\Indexer\\IndexerInterface.php';
include_once \dirname(__DIR__, 4).'\\vendor\\contao\\core-bundle\\src\\Search\\Indexer\\DelegatingIndexer.php';
include_once \dirname(__DIR__, 4).'\\vendor\\contao\\core-bundle\\src\\Search\\Indexer\\DefaultIndexer.php';

$this->services['contao.search.indexer'] = $instance = new \Contao\CoreBundle\Search\Indexer\DelegatingIndexer();

$instance->addIndexer(new \Contao\CoreBundle\Search\Indexer\DefaultIndexer(($this->services['contao.framework'] ?? $this->getContao_FrameworkService()), ($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()), false));

return $instance;
