<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'contao.listener.Z6uZ2NA' shared service.

include_once \dirname(__DIR__, 4).'\\vendor\\contao\\core-bundle\\src\\EventListener\\GlobalsMapListener.php';

return $this->services['contao.listener.Z6uZ2NA'] = new \Contao\CoreBundle\EventListener\GlobalsMapListener(['FE_MOD' => ['user' => ['two_factor' => 'Contao\\ModuleProxy']]]);
