<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.security.voter.scheb_two_factor.security.access.authenticated_voter' shared service.

include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\security-core\\Authorization\\Voter\\TraceableVoter.php';
include_once \dirname(__DIR__, 4).'\\vendor\\scheb\\two-factor-bundle\\Security\\Authorization\\Voter\\TwoFactorInProgressVoter.php';

return $this->privates['debug.security.voter.scheb_two_factor.security.access.authenticated_voter'] = new \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter(new \Scheb\TwoFactorBundle\Security\Authorization\Voter\TwoFactorInProgressVoter(), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
