<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQFMnpqL\appContao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQFMnpqL/appContao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQFMnpqL.legacy');

    return;
}

if (!\class_exists(appContao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQFMnpqL\appContao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer::class, appContao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer::class, false);
}

return new \ContainerQFMnpqL\appContao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer([
    'container.build_hash' => 'QFMnpqL',
    'container.build_id' => '3a2edfe6',
    'container.build_time' => 1591281564,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQFMnpqL');
