<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.command.debug_fragments' shared service.

include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\console\\Command\\Command.php';
include_once \dirname(__DIR__, 4).'\\vendor\\contao\\core-bundle\\src\\Command\\DebugFragmentsCommand.php';

$this->privates['contao.command.debug_fragments'] = $instance = new \Contao\CoreBundle\Command\DebugFragmentsCommand();

$instance->add('contao.frontend_module.two_factor', ($this->privates['contao.fragment._config_gcOFWMz'] ?? ($this->privates['contao.fragment._config_gcOFWMz'] = new \Contao\CoreBundle\Fragment\FragmentConfig('Contao\\CoreBundle\\Controller\\FrontendModule\\TwoFactorController', 'forward', ['ignore_errors' => false]))), ['category' => 'user', 'type' => 'two_factor']);
$instance->setName('debug:fragments');

return $instance;
