<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.contao.command.resize_images' shared service.

include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\console\\Command\\Command.php';
include_once \dirname(__DIR__, 4).'\\vendor\\contao\\core-bundle\\src\\Command\\ResizeImagesCommand.php';

return $this->services['console.command.public_alias.contao.command.resize_images'] = new \Contao\CoreBundle\Command\ResizeImagesCommand(($this->services['contao.image.image_factory'] ?? $this->load('getContao_Image_ImageFactoryService.php')), ($this->services['contao.image.resizer'] ?? $this->load('getContao_Image_ResizerService.php')), (\dirname(__DIR__, 4).'/assets/images'), ($this->privates['contao.image.deferred_image_storage'] ?? $this->load('getContao_Image_DeferredImageStorageService.php')), ($this->services['filesystem'] ?? ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem())));
