<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.security.voter.contao.security.backend_access_voter' shared service.

include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\security-core\\Authorization\\Voter\\TraceableVoter.php';
include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\security-core\\Authorization\\Voter\\Voter.php';
include_once \dirname(__DIR__, 4).'\\vendor\\contao\\core-bundle\\src\\Security\\Voter\\BackendAccessVoter.php';

return $this->privates['debug.security.voter.contao.security.backend_access_voter'] = new \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter(new \Contao\CoreBundle\Security\Voter\BackendAccessVoter(), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
